import {useLanguage} from '../languages';
import {ImageURISource} from 'react-native';

//*  It is the database file.
//*  This (file) is used to store the 'database' of all products.

//* Products Interface
export interface IProducts {
  name: string;
  icon: ImageURISource;
  type: 'normal' | 'root' | 'cluster' | 'grass' | 'straw';
  avgPriceEasy: number;
  avgPriceMedium: number;
  avgPriceHard: number;
  yieldPerHa: number;
  strawPerHa?: number;
  unit: string;
}

//* Function to simulate a database of Animals Products
export function useAnimals(): Array<IProducts> {
  const {string} = useLanguage();
  return [
    {
      name: string.silage,
      icon: require('../assets/crops/silage.png'),
      type: 'normal',
      avgPriceEasy: 3,
      avgPriceMedium: 2,
      avgPriceHard: 1,
      yieldPerHa: 87395,
      unit: string.liters,
    },
  ];
}

//* Function to simulate a database of Harvest Products
export function useCrops(): Array<IProducts> {
  //* Language hook declaration
  const {string} = useLanguage();

  return [
    {
      name: string.wheat,
      icon: require('../assets/crops/wheat.png'),
      type: 'normal',
      avgPriceEasy: 3,
      avgPriceMedium: 2,
      avgPriceHard: 1,
      yieldPerHa: 8900,
      strawPerHa: 36400,
      unit: string.liters,
    },
    {
      name: string.barley,
      icon: require('../assets/crops/barley.png'),
      type: 'normal',
      avgPriceEasy: 3,
      avgPriceMedium: 2,
      avgPriceHard: 1,
      yieldPerHa: 9600,
      strawPerHa: 36450,
      unit: string.liters,
    },
    {
      name: string.oat,
      icon: require('../assets/crops/oat.png'),
      type: 'normal',
      avgPriceEasy: 3,
      avgPriceMedium: 2,
      avgPriceHard: 1,
      yieldPerHa: 5700,
      strawPerHa: 36500,
      unit: string.liters,
    },
    {
      name: string.canola,
      icon: require('../assets/crops/canola.png'),
      type: 'normal',
      avgPriceEasy: 3,
      avgPriceMedium: 2,
      avgPriceHard: 1,
      yieldPerHa: 5800,
      unit: string.liters,
    },
    {
      name: string.sorghum,
      icon: require('../assets/crops/sorghum.png'),
      type: 'normal',
      avgPriceEasy: 3,
      avgPriceMedium: 2,
      avgPriceHard: 1,
      yieldPerHa: 8200,
      unit: string.liters,
    },
    {
      name: string.grapes,
      icon: require('../assets/crops/grapes.png'),
      type: 'cluster',
      avgPriceEasy: 3,
      avgPriceMedium: 2,
      avgPriceHard: 1,
      yieldPerHa: 9200,
      unit: string.liters,
    },
    {
      name: string.olives,
      icon: require('../assets/crops/olives.png'),
      type: 'cluster',
      avgPriceEasy: 3,
      avgPriceMedium: 2,
      avgPriceHard: 1,
      yieldPerHa: 9200,
      unit: string.liters,
    },
    {
      name: string.sunflowers,
      icon: require('../assets/crops/sunflowers.png'),
      type: 'normal',
      avgPriceEasy: 3,
      avgPriceMedium: 2,
      avgPriceHard: 1,
      yieldPerHa: 5200,
      unit: string.liters,
    },
    {
      name: string.soybeans,
      icon: require('../assets/crops/soybeans.png'),
      type: 'normal',
      avgPriceEasy: 3,
      avgPriceMedium: 2,
      avgPriceHard: 1,
      yieldPerHa: 4500,
      unit: string.liters,
    },
    {
      name: string.corn,
      icon: require('../assets/crops/corn.png'),
      type: 'normal',
      avgPriceEasy: 3,
      avgPriceMedium: 2,
      avgPriceHard: 1,
      yieldPerHa: 9200,
      unit: string.liters,
    },
    {
      name: string.potatoes,
      icon: require('../assets/crops/potatoes.png'),
      type: 'root',
      avgPriceEasy: 3,
      avgPriceMedium: 2,
      avgPriceHard: 1,
      yieldPerHa: 41300,
      unit: string.liters,
    },
    {
      name: string.sugar_beet,
      icon: require('../assets/crops/sugar_beet.png'),
      type: 'root',
      avgPriceEasy: 3,
      avgPriceMedium: 2,
      avgPriceHard: 1,
      yieldPerHa: 57800,
      unit: string.liters,
    },
    {
      name: string.cotton,
      icon: require('../assets/crops/cotton.png'),
      type: 'normal',
      avgPriceEasy: 3,
      avgPriceMedium: 2,
      avgPriceHard: 1,
      yieldPerHa: 4970,
      unit: string.liters,
    },
    {
      name: string.sugarcane,
      icon: require('../assets/crops/sugarcane.png'),
      type: 'root',
      avgPriceEasy: 3,
      avgPriceMedium: 2,
      avgPriceHard: 1,
      yieldPerHa: 113400,
      unit: string.liters,
    },
    {
      name: string.grass_cut,
      icon: require('../assets/crops/grass_cut.png'),
      type: 'grass',
      avgPriceEasy: 3,
      avgPriceMedium: 2,
      avgPriceHard: 1,
      yieldPerHa: 87395,
      unit: string.liters,
    },
    {
      name: string.hay,
      icon: require('../assets/crops/hay.png'),
      type: 'grass',
      avgPriceEasy: 3,
      avgPriceMedium: 2,
      avgPriceHard: 1,
      yieldPerHa: 87395,
      unit: string.liters,
    },
    {
      name: string.straw,
      icon: require('../assets/crops/straw.png'),
      type: 'straw',
      avgPriceEasy: 3,
      avgPriceMedium: 2,
      avgPriceHard: 1,
      yieldPerHa: 1,
      unit: string.liters,
    },
    {
      name: string.poplar_tree,
      icon: require('../assets/crops/poplar_tree.png'),
      type: 'normal',
      avgPriceEasy: 3,
      avgPriceMedium: 2,
      avgPriceHard: 1,
      yieldPerHa: 1,
      unit: string.liters,
    },
    // {
    //   name: string.chafft,
    //   icon: require('../assets/crops/chafft.png'),
    //   type: 'normal',
    //   avgPriceEasy: 3,
    //   avgPriceMedium: 2,
    //   avgPriceHard: 1,
    //   yieldPerHa: 87395,
    //   unit: string.liters,
    // },
    // {
    //   name: string.cotton_round_bale,
    //   icon: require('../assets/crops/cotton_round_bale.png'),
    //   type: 'normal',
    //   avgPriceEasy: 3,
    //   avgPriceMedium: 2,
    //   avgPriceHard: 1,
    //   yieldPerHa: 1,
    //   unit: string.unit,
    // },
    // {
    //   name: string.cotton_square_bale,
    //   icon: require('../assets/crops/cotton_square_bale.png'),
    //   type: 'normal',
    //   avgPriceEasy: 3,
    //   avgPriceMedium: 2,
    //   avgPriceHard: 1,
    //   yieldPerHa: 1,
    //   unit: string.unit,
    // },
    // {
    //   name: string.fir_tree,
    //   icon: require('../assets/crops/fir_tree.png'),
    //   type: 'normal',
    //   avgPriceEasy: 3,
    //   avgPriceMedium: 2,
    //   avgPriceHard: 1,
    //   yieldPerHa: 1,
    //   unit: string.liters,
    // },
    // {
    //   name: string.grass,
    //   icon: require('../assets/crops/grass.png'),
    //   type: 'normal',
    //   avgPriceEasy: 3,
    //   avgPriceMedium: 2,
    //   avgPriceHard: 1,
    //   yieldPerHa: 87395,
    //   unit: string.liters,
    // },
    // {
    //   name: string.silage,
    //   icon: require('../assets/crops/silage.png'),
    //   type: 'normal',
    //   avgPriceEasy: 3,
    //   avgPriceMedium: 2,
    //   avgPriceHard: 1,
    //   yieldPerHa: 87395,
    //   unit: string.liters,
    // },
    // {
    //   name: string.straw_round_bale,
    //   icon: require('../assets/crops/straw_round_bale.png'),
    //   type: 'normal',
    //   avgPriceEasy: 3,
    //   avgPriceMedium: 2,
    //   avgPriceHard: 1,
    //   yieldPerHa: 1,
    //   unit: string.unit,
    // },
    // {
    //   name: string.straw_square_bale,
    //   icon: require('../assets/crops/straw_square_bale.png'),
    //   type: 'normal',
    //   avgPriceEasy: 3,
    //   avgPriceMedium: 2,
    //   avgPriceHard: 1,
    //   yieldPerHa: 1,
    //   unit: string.unit,
    // },
    // {
    //   name: string.sugar_beet_cut,
    //   icon: require('../assets/crops/sugar_beet_cut.png'),
    //   type: 'root',
    //   avgPriceEasy: 3,
    //   avgPriceMedium: 2,
    //   avgPriceHard: 1,
    //   yieldPerHa: 57800,
    //   unit: string.liters,
    // },
    // {
    //   name: string.wood_chips,
    //   icon: require('../assets/crops/wood_chips.png'),
    //   type: 'normal',
    //   avgPriceEasy: 3,
    //   avgPriceMedium: 2,
    //   avgPriceHard: 1,
    //   yieldPerHa: 1,
    //   unit: string.liters,
    // },
    // {
    //   name: string.wood_chips_round_bale,
    //   icon: require('../assets/crops/wood_chips_round_bale.png'),
    //   type: 'normal',
    //   avgPriceEasy: 3,
    //   avgPriceMedium: 2,
    //   avgPriceHard: 1,
    //   yieldPerHa: 1,
    //   unit: string.unit,
    // },
    // {
    //   name: string.wood_chips_square_bale,
    //   icon: require('../assets/crops/wood_chips_square_bale.png'),
    //   type: 'normal',
    //   avgPriceEasy: 3,
    //   avgPriceMedium: 2,
    //   avgPriceHard: 1,
    //   yieldPerHa: 1,
    //   unit: string.unit,
    // },
  ];
}
